---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        #- id: check-added-large-files
      - id: check-ast
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.5
    hooks:
      - id: clang-format
        "types_or": [c++, c]
        args:
          - "-style=file"
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "3.0.3" # pick a git hash / tag to point to
    hooks:
      - id: editorconfig-checker
        alias: ec
  - repo: https://github.com/yoheimuta/protolint
    rev: "v0.51.0"
    hooks:
      - id: protolint
        args: ["-fix", "-auto_disable=this"]
